<?xml version="1.0" encoding="UTF-8"?>
<project name="CSC191_GUI_Lab" default="jar" basedir=".">
    <property file="nbproject/project.properties"/>

    <target name="init">
        <mkdir dir="${build.classes.dir}"/>
        <mkdir dir="${dist.dir}"/>
    </target>

    <target name="compile" depends="init">
        <javac srcdir="${src.dir}"
               destdir="${build.classes.dir}"
               includeantruntime="false"
               source="${javac.source}"
               target="${javac.target}"
               encoding="UTF-8"/>
    </target>

    <target name="jar" depends="compile">
        <jar destfile="${dist.jar}" basedir="${build.classes.dir}">
            <manifest>
                <attribute name="Main-Class" value="${main.class}"/>
            </manifest>
        </jar>
    </target>

    <target name="run" depends="compile">
        <java classname="${main.class}" fork="true" failonerror="true">
            <classpath>
                <pathelement path="${build.classes.dir}"/>
            </classpath>
        </java>
    </target>

    <target name="clean">
        <delete dir="${build.dir}"/>
        <delete dir="${dist.dir}"/>
    </target>
</project>
